var hierarchy =
[
    [ "Adafruit_NeoPixel", "class_adafruit___neo_pixel.html", null ],
    [ "AddAppDependencyResult_t", "struct_add_app_dependency_result__t.html", null ],
    [ "Valve.Steamworks.AddAppDependencyResult_t", "struct_valve_1_1_steamworks_1_1_add_app_dependency_result__t.html", null ],
    [ "AddUGCDependencyResult_t", "struct_add_u_g_c_dependency_result__t.html", null ],
    [ "Valve.Steamworks.AddUGCDependencyResult_t", "struct_valve_1_1_steamworks_1_1_add_u_g_c_dependency_result__t.html", null ],
    [ "AppProofOfPurchaseKeyResponse_t", "struct_app_proof_of_purchase_key_response__t.html", null ],
    [ "Valve.Steamworks.AppProofOfPurchaseKeyResponse_t", "struct_valve_1_1_steamworks_1_1_app_proof_of_purchase_key_response__t.html", null ],
    [ "AssociateWithClanResult_t", "struct_associate_with_clan_result__t.html", null ],
    [ "Valve.Steamworks.AssociateWithClanResult_t", "struct_valve_1_1_steamworks_1_1_associate_with_clan_result__t.html", null ],
    [ "Valve.Steamworks.AvatarImageLoaded_t", "struct_valve_1_1_steamworks_1_1_avatar_image_loaded__t.html", null ],
    [ "AvatarImageLoaded_t", "struct_avatar_image_loaded__t.html", null ],
    [ "BackEnd", "class_back_end.html", null ],
    [ "Valve.Steamworks.CAddAppDependencyResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_add_app_dependency_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CAddUGCDependencyResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_add_u_g_c_dependency_result__t___call_result.html", null ],
    [ "CallbackMsg_t", "struct_callback_msg__t.html", null ],
    [ "Valve.Steamworks.CallbackMsg_t", "struct_valve_1_1_steamworks_1_1_callback_msg__t.html", null ],
    [ "Valve.Steamworks.CAssociateWithClanResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_associate_with_clan_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CCallback", "struct_valve_1_1_steamworks_1_1_c_callback.html", null ],
    [ "CCallbackBase", "class_c_callback_base.html", [
      [ "CCallbackImpl< sizeof_P >", "class_c_callback_impl.html", null ],
      [ "CCallbackImpl< sizeof(P) >", "class_c_callback_impl.html", [
        [ "CCallback< T, P, bGameserver >", "class_c_callback.html", null ],
        [ "CCallback< T, P, bGameServer >", "class_c_callback.html", [
          [ "CCallbackManual< T, P, bGameServer >", "class_c_callback_manual.html", null ]
        ] ]
      ] ],
      [ "CCallResult< T, P >", "class_c_call_result.html", null ]
    ] ],
    [ "Valve.Steamworks.CCallbackBase", "struct_valve_1_1_steamworks_1_1_c_callback_base.html", null ],
    [ "Valve.Steamworks.CCallResult", "struct_valve_1_1_steamworks_1_1_c_call_result.html", null ],
    [ "Valve.Steamworks.CCheckFileSignature_t_CallResult", "class_valve_1_1_steamworks_1_1_c_check_file_signature__t___call_result.html", null ],
    [ "Valve.Steamworks.CClanOfficerListResponse_t_CallResult", "class_valve_1_1_steamworks_1_1_c_clan_officer_list_response__t___call_result.html", null ],
    [ "Valve.Steamworks.CComputeNewPlayerCompatibilityResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_compute_new_player_compatibility_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CCreateItemResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_create_item_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CDeleteItemResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_delete_item_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CEncryptedAppTicketResponse_t_CallResult", "class_valve_1_1_steamworks_1_1_c_encrypted_app_ticket_response__t___call_result.html", null ],
    [ "Valve.Steamworks.CFileDetailsResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_file_details_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CFriendsEnumerateFollowingList_t_CallResult", "class_valve_1_1_steamworks_1_1_c_friends_enumerate_following_list__t___call_result.html", null ],
    [ "Valve.Steamworks.CFriendsGetFollowerCount_t_CallResult", "class_valve_1_1_steamworks_1_1_c_friends_get_follower_count__t___call_result.html", null ],
    [ "Valve.Steamworks.CFriendsIsFollowing_t_CallResult", "class_valve_1_1_steamworks_1_1_c_friends_is_following__t___call_result.html", null ],
    [ "CGameID", "class_c_game_i_d.html", null ],
    [ "Valve.Steamworks.CGetAppDependenciesResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_get_app_dependencies_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CGetOPFSettingsResult_t_Callback", "class_valve_1_1_steamworks_1_1_c_get_o_p_f_settings_result__t___callback.html", null ],
    [ "Valve.Steamworks.CGetUserItemVoteResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_get_user_item_vote_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CGlobalAchievementPercentagesReady_t_CallResult", "class_valve_1_1_steamworks_1_1_c_global_achievement_percentages_ready__t___call_result.html", null ],
    [ "Valve.Steamworks.CGlobalStatsReceived_t_CallResult", "class_valve_1_1_steamworks_1_1_c_global_stats_received__t___call_result.html", null ],
    [ "Valve.Steamworks.CGSReputation_t_CallResult", "class_valve_1_1_steamworks_1_1_c_g_s_reputation__t___call_result.html", null ],
    [ "Valve.Steamworks.CGSStatsReceived_t_CallResult", "class_valve_1_1_steamworks_1_1_c_g_s_stats_received__t___call_result.html", null ],
    [ "Valve.Steamworks.CGSStatsStored_t_CallResult", "class_valve_1_1_steamworks_1_1_c_g_s_stats_stored__t___call_result.html", null ],
    [ "CheckFileSignature_t", "struct_check_file_signature__t.html", null ],
    [ "Valve.Steamworks.CheckFileSignature_t", "struct_valve_1_1_steamworks_1_1_check_file_signature__t.html", null ],
    [ "Valve.Steamworks.CHTML_BrowserReady_t_CallResult", "class_valve_1_1_steamworks_1_1_c_h_t_m_l___browser_ready__t___call_result.html", null ],
    [ "Valve.Steamworks.CJoinClanChatRoomCompletionResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_join_clan_chat_room_completion_result__t___call_result.html", null ],
    [ "Valve.Steamworks.ClanOfficerListResponse_t", "struct_valve_1_1_steamworks_1_1_clan_officer_list_response__t.html", null ],
    [ "ClanOfficerListResponse_t", "struct_clan_officer_list_response__t.html", null ],
    [ "Valve.Steamworks.CLeaderboardFindResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_leaderboard_find_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CLeaderboardScoresDownloaded_t_CallResult", "class_valve_1_1_steamworks_1_1_c_leaderboard_scores_downloaded__t___call_result.html", null ],
    [ "Valve.Steamworks.CLeaderboardScoreUploaded_t_CallResult", "class_valve_1_1_steamworks_1_1_c_leaderboard_score_uploaded__t___call_result.html", null ],
    [ "Valve.Steamworks.CLeaderboardUGCSet_t_CallResult", "class_valve_1_1_steamworks_1_1_c_leaderboard_u_g_c_set__t___call_result.html", null ],
    [ "ClientGameServerDeny_t", "struct_client_game_server_deny__t.html", null ],
    [ "Valve.Steamworks.ClientGameServerDeny_t", "struct_valve_1_1_steamworks_1_1_client_game_server_deny__t.html", null ],
    [ "Valve.Steamworks.CLobbyCreated_t_CallResult", "class_valve_1_1_steamworks_1_1_c_lobby_created__t___call_result.html", null ],
    [ "Valve.Steamworks.CLobbyEnter_t_CallResult", "class_valve_1_1_steamworks_1_1_c_lobby_enter__t___call_result.html", null ],
    [ "Valve.Steamworks.CLobbyMatchList_t_CallResult", "class_valve_1_1_steamworks_1_1_c_lobby_match_list__t___call_result.html", null ],
    [ "Valve.Steamworks.CNumberOfCurrentPlayers_t_CallResult", "class_valve_1_1_steamworks_1_1_c_number_of_current_players__t___call_result.html", null ],
    [ "ComputeNewPlayerCompatibilityResult_t", "struct_compute_new_player_compatibility_result__t.html", null ],
    [ "Valve.Steamworks.ComputeNewPlayerCompatibilityResult_t", "struct_valve_1_1_steamworks_1_1_compute_new_player_compatibility_result__t.html", null ],
    [ "ControllerAnalogActionData_t", "struct_controller_analog_action_data__t.html", null ],
    [ "Valve.Steamworks.ControllerAnalogActionData_t", "struct_valve_1_1_steamworks_1_1_controller_analog_action_data__t.html", null ],
    [ "Valve.Steamworks.ControllerDigitalActionData_t", "struct_valve_1_1_steamworks_1_1_controller_digital_action_data__t.html", null ],
    [ "ControllerDigitalActionData_t", "struct_controller_digital_action_data__t.html", null ],
    [ "Valve.Steamworks.ControllerMotionData_t", "struct_valve_1_1_steamworks_1_1_controller_motion_data__t.html", null ],
    [ "ControllerMotionData_t", "struct_controller_motion_data__t.html", null ],
    [ "CreateItemResult_t", "struct_create_item_result__t.html", null ],
    [ "Valve.Steamworks.CreateItemResult_t", "struct_valve_1_1_steamworks_1_1_create_item_result__t.html", null ],
    [ "Valve.Steamworks.CRemoteStorageDeletePublishedFileResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_delete_published_file_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageDownloadUGCResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_download_u_g_c_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageEnumeratePublishedFilesByUserActionResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_enumerate_published_files_by_user_action_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageEnumerateUserPublishedFilesResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_enumerate_user_published_files_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageEnumerateUserSubscribedFilesResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_enumerate_user_subscribed_files_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageEnumerateWorkshopFilesResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_enumerate_workshop_files_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageFileReadAsyncComplete_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_file_read_async_complete__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageFileShareResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_file_share_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageFileWriteAsyncComplete_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_file_write_async_complete__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageGetPublishedFileDetailsResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_get_published_file_details_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageGetPublishedItemVoteDetailsResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_get_published_item_vote_details_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStoragePublishFileProgress_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_publish_file_progress__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageSetUserPublishedFileActionResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_set_user_published_file_action_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageSubscribePublishedFileResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_subscribe_published_file_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageUnsubscribePublishedFileResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_unsubscribe_published_file_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageUpdatePublishedFileResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_update_published_file_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoteStorageUpdateUserPublishedItemVoteResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remote_storage_update_user_published_item_vote_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoveAppDependencyResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remove_app_dependency_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CRemoveUGCDependencyResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_remove_u_g_c_dependency_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CSetPersonaNameResponse_t_CallResult", "class_valve_1_1_steamworks_1_1_c_set_persona_name_response__t___call_result.html", null ],
    [ "Valve.Steamworks.CSetUserItemVoteResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_set_user_item_vote_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CStartPlaytimeTrackingResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_start_playtime_tracking_result__t___call_result.html", null ],
    [ "CSteamAPIContext", "class_c_steam_a_p_i_context.html", null ],
    [ "Valve.Steamworks.CSteamAPIContext", "struct_valve_1_1_steamworks_1_1_c_steam_a_p_i_context.html", null ],
    [ "CSteamGameServerAPIContext", "class_c_steam_game_server_a_p_i_context.html", null ],
    [ "Valve.Steamworks.CSteamID", "struct_valve_1_1_steamworks_1_1_c_steam_i_d.html", null ],
    [ "CSteamID", "class_c_steam_i_d.html", null ],
    [ "Valve.Steamworks.CSteamInventoryEligiblePromoItemDefIDs_t_CallResult", "class_valve_1_1_steamworks_1_1_c_steam_inventory_eligible_promo_item_def_i_ds__t___call_result.html", null ],
    [ "Valve.Steamworks.CSteamUGCQueryCompleted_t_CallResult", "class_valve_1_1_steamworks_1_1_c_steam_u_g_c_query_completed__t___call_result.html", null ],
    [ "Valve.Steamworks.CStopPlaytimeTrackingResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_stop_playtime_tracking_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CStoreAuthURLResponse_t_CallResult", "class_valve_1_1_steamworks_1_1_c_store_auth_u_r_l_response__t___call_result.html", null ],
    [ "Valve.Steamworks.CSubmitItemUpdateResult_t_CallResult", "class_valve_1_1_steamworks_1_1_c_submit_item_update_result__t___call_result.html", null ],
    [ "Valve.Steamworks.CUserFavoriteItemsListChanged_t_CallResult", "class_valve_1_1_steamworks_1_1_c_user_favorite_items_list_changed__t___call_result.html", null ],
    [ "Valve.Steamworks.CUserStatsReceived_t_Callback", "class_valve_1_1_steamworks_1_1_c_user_stats_received__t___callback.html", null ],
    [ "Valve.Steamworks.CUserStatsReceived_t_CallResult", "class_valve_1_1_steamworks_1_1_c_user_stats_received__t___call_result.html", null ],
    [ "DeleteItemResult_t", "struct_delete_item_result__t.html", null ],
    [ "Valve.Steamworks.DeleteItemResult_t", "struct_valve_1_1_steamworks_1_1_delete_item_result__t.html", null ],
    [ "DlcInstalled_t", "struct_dlc_installed__t.html", null ],
    [ "Valve.Steamworks.DlcInstalled_t", "struct_valve_1_1_steamworks_1_1_dlc_installed__t.html", null ],
    [ "Valve.Steamworks.DownloadClanActivityCountsResult_t", "struct_valve_1_1_steamworks_1_1_download_clan_activity_counts_result__t.html", null ],
    [ "DownloadClanActivityCountsResult_t", "struct_download_clan_activity_counts_result__t.html", null ],
    [ "DownloadItemResult_t", "struct_download_item_result__t.html", null ],
    [ "Valve.Steamworks.DownloadItemResult_t", "struct_valve_1_1_steamworks_1_1_download_item_result__t.html", null ],
    [ "DS1307", "class_d_s1307.html", null ],
    [ "Valve.Steamworks.EncryptedAppTicketResponse_t", "struct_valve_1_1_steamworks_1_1_encrypted_app_ticket_response__t.html", null ],
    [ "EncryptedAppTicketResponse_t", "struct_encrypted_app_ticket_response__t.html", null ],
    [ "FavoritesListAccountsUpdated_t", "struct_favorites_list_accounts_updated__t.html", null ],
    [ "Valve.Steamworks.FavoritesListAccountsUpdated_t", "struct_valve_1_1_steamworks_1_1_favorites_list_accounts_updated__t.html", null ],
    [ "FavoritesListChanged_t", "struct_favorites_list_changed__t.html", null ],
    [ "Valve.Steamworks.FavoritesListChanged_t", "struct_valve_1_1_steamworks_1_1_favorites_list_changed__t.html", null ],
    [ "FileDetailsResult_t", "struct_file_details_result__t.html", null ],
    [ "Valve.Steamworks.FileDetailsResult_t", "struct_valve_1_1_steamworks_1_1_file_details_result__t.html", null ],
    [ "FriendGameInfo_t", "struct_friend_game_info__t.html", null ],
    [ "Valve.Steamworks.FriendGameInfo_t", "struct_valve_1_1_steamworks_1_1_friend_game_info__t.html", null ],
    [ "Valve.Steamworks.FriendRichPresenceUpdate_t", "struct_valve_1_1_steamworks_1_1_friend_rich_presence_update__t.html", null ],
    [ "FriendRichPresenceUpdate_t", "struct_friend_rich_presence_update__t.html", null ],
    [ "FriendsEnumerateFollowingList_t", "struct_friends_enumerate_following_list__t.html", null ],
    [ "Valve.Steamworks.FriendsEnumerateFollowingList_t", "struct_valve_1_1_steamworks_1_1_friends_enumerate_following_list__t.html", null ],
    [ "FriendSessionStateInfo_t", "struct_friend_session_state_info__t.html", null ],
    [ "Valve.Steamworks.FriendSessionStateInfo_t", "struct_valve_1_1_steamworks_1_1_friend_session_state_info__t.html", null ],
    [ "FriendsGetFollowerCount_t", "struct_friends_get_follower_count__t.html", null ],
    [ "Valve.Steamworks.FriendsGetFollowerCount_t", "struct_valve_1_1_steamworks_1_1_friends_get_follower_count__t.html", null ],
    [ "FriendsIsFollowing_t", "struct_friends_is_following__t.html", null ],
    [ "Valve.Steamworks.FriendsIsFollowing_t", "struct_valve_1_1_steamworks_1_1_friends_is_following__t.html", null ],
    [ "FrontEnd", "class_front_end.html", null ],
    [ "Valve.Steamworks.GameConnectedChatJoin_t", "struct_valve_1_1_steamworks_1_1_game_connected_chat_join__t.html", null ],
    [ "GameConnectedChatJoin_t", "struct_game_connected_chat_join__t.html", null ],
    [ "Valve.Steamworks.GameConnectedChatLeave_t", "struct_valve_1_1_steamworks_1_1_game_connected_chat_leave__t.html", null ],
    [ "GameConnectedChatLeave_t", "struct_game_connected_chat_leave__t.html", null ],
    [ "Valve.Steamworks.GameConnectedClanChatMsg_t", "struct_valve_1_1_steamworks_1_1_game_connected_clan_chat_msg__t.html", null ],
    [ "GameConnectedClanChatMsg_t", "struct_game_connected_clan_chat_msg__t.html", null ],
    [ "GameConnectedFriendChatMsg_t", "struct_game_connected_friend_chat_msg__t.html", null ],
    [ "Valve.Steamworks.GameConnectedFriendChatMsg_t", "struct_valve_1_1_steamworks_1_1_game_connected_friend_chat_msg__t.html", null ],
    [ "Valve.Steamworks.GameID_t", "struct_valve_1_1_steamworks_1_1_game_i_d__t.html", null ],
    [ "Valve.Steamworks.GameLobbyJoinRequested_t", "struct_valve_1_1_steamworks_1_1_game_lobby_join_requested__t.html", null ],
    [ "GameLobbyJoinRequested_t", "struct_game_lobby_join_requested__t.html", null ],
    [ "GameOverlayActivated_t", "struct_game_overlay_activated__t.html", null ],
    [ "Valve.Steamworks.GameOverlayActivated_t", "struct_valve_1_1_steamworks_1_1_game_overlay_activated__t.html", null ],
    [ "Valve.Steamworks.GamepadTextInputDismissed_t", "struct_valve_1_1_steamworks_1_1_gamepad_text_input_dismissed__t.html", null ],
    [ "GamepadTextInputDismissed_t", "struct_gamepad_text_input_dismissed__t.html", null ],
    [ "Valve.Steamworks.GameRichPresenceJoinRequested_t", "struct_valve_1_1_steamworks_1_1_game_rich_presence_join_requested__t.html", null ],
    [ "GameRichPresenceJoinRequested_t", "struct_game_rich_presence_join_requested__t.html", null ],
    [ "Valve.Steamworks.GameServerChangeRequested_t", "struct_valve_1_1_steamworks_1_1_game_server_change_requested__t.html", null ],
    [ "GameServerChangeRequested_t", "struct_game_server_change_requested__t.html", null ],
    [ "Valve.Steamworks.gameserveritem_t", "struct_valve_1_1_steamworks_1_1gameserveritem__t.html", null ],
    [ "gameserveritem_t", "classgameserveritem__t.html", null ],
    [ "GameWebCallback_t", "struct_game_web_callback__t.html", null ],
    [ "Valve.Steamworks.GameWebCallback_t", "struct_valve_1_1_steamworks_1_1_game_web_callback__t.html", null ],
    [ "GCMessageAvailable_t", "struct_g_c_message_available__t.html", null ],
    [ "GCMessageFailed_t", "struct_g_c_message_failed__t.html", null ],
    [ "GetAppDependenciesResult_t", "struct_get_app_dependencies_result__t.html", null ],
    [ "Valve.Steamworks.GetAppDependenciesResult_t", "struct_valve_1_1_steamworks_1_1_get_app_dependencies_result__t.html", null ],
    [ "GetAuthSessionTicketResponse_t", "struct_get_auth_session_ticket_response__t.html", null ],
    [ "Valve.Steamworks.GetAuthSessionTicketResponse_t", "struct_valve_1_1_steamworks_1_1_get_auth_session_ticket_response__t.html", null ],
    [ "GetUserItemVoteResult_t", "struct_get_user_item_vote_result__t.html", null ],
    [ "Valve.Steamworks.GetUserItemVoteResult_t", "struct_valve_1_1_steamworks_1_1_get_user_item_vote_result__t.html", null ],
    [ "GlobalAchievementPercentagesReady_t", "struct_global_achievement_percentages_ready__t.html", null ],
    [ "Valve.Steamworks.GlobalAchievementPercentagesReady_t", "struct_valve_1_1_steamworks_1_1_global_achievement_percentages_ready__t.html", null ],
    [ "GlobalStatsReceived_t", "struct_global_stats_received__t.html", null ],
    [ "Valve.Steamworks.GlobalStatsReceived_t", "struct_valve_1_1_steamworks_1_1_global_stats_received__t.html", null ],
    [ "GSClientAchievementStatus_t", "struct_g_s_client_achievement_status__t.html", null ],
    [ "Valve.Steamworks.GSClientAchievementStatus_t", "struct_valve_1_1_steamworks_1_1_g_s_client_achievement_status__t.html", null ],
    [ "GSClientApprove_t", "struct_g_s_client_approve__t.html", null ],
    [ "Valve.Steamworks.GSClientApprove_t", "struct_valve_1_1_steamworks_1_1_g_s_client_approve__t.html", null ],
    [ "Valve.Steamworks.GSClientDeny_t", "struct_valve_1_1_steamworks_1_1_g_s_client_deny__t.html", null ],
    [ "GSClientDeny_t", "struct_g_s_client_deny__t.html", null ],
    [ "GSClientGroupStatus_t", "struct_g_s_client_group_status__t.html", null ],
    [ "Valve.Steamworks.GSClientGroupStatus_t", "struct_valve_1_1_steamworks_1_1_g_s_client_group_status__t.html", null ],
    [ "Valve.Steamworks.GSClientKick_t", "struct_valve_1_1_steamworks_1_1_g_s_client_kick__t.html", null ],
    [ "GSClientKick_t", "struct_g_s_client_kick__t.html", null ],
    [ "GSGameplayStats_t", "struct_g_s_gameplay_stats__t.html", null ],
    [ "Valve.Steamworks.GSGameplayStats_t", "struct_valve_1_1_steamworks_1_1_g_s_gameplay_stats__t.html", null ],
    [ "Valve.Steamworks.GSPolicyResponse_t", "struct_valve_1_1_steamworks_1_1_g_s_policy_response__t.html", null ],
    [ "GSPolicyResponse_t", "struct_g_s_policy_response__t.html", null ],
    [ "GSReputation_t", "struct_g_s_reputation__t.html", null ],
    [ "Valve.Steamworks.GSReputation_t", "struct_valve_1_1_steamworks_1_1_g_s_reputation__t.html", null ],
    [ "GSStatsReceived_t", "struct_g_s_stats_received__t.html", null ],
    [ "Valve.Steamworks.GSStatsReceived_t", "struct_valve_1_1_steamworks_1_1_g_s_stats_received__t.html", null ],
    [ "Valve.Steamworks.GSStatsStored_t", "struct_valve_1_1_steamworks_1_1_g_s_stats_stored__t.html", null ],
    [ "GSStatsStored_t", "struct_g_s_stats_stored__t.html", null ],
    [ "GSStatsUnloaded_t", "struct_g_s_stats_unloaded__t.html", null ],
    [ "Valve.Steamworks.GSStatsUnloaded_t", "struct_valve_1_1_steamworks_1_1_g_s_stats_unloaded__t.html", null ],
    [ "Valve.Steamworks.HTML_BrowserReady_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___browser_ready__t.html", null ],
    [ "Valve.Steamworks.HTML_CanGoBackAndForward_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___can_go_back_and_forward__t.html", null ],
    [ "Valve.Steamworks.HTML_ChangedTitle_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___changed_title__t.html", null ],
    [ "Valve.Steamworks.HTML_CloseBrowser_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___close_browser__t.html", null ],
    [ "Valve.Steamworks.HTML_FileOpenDialog_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___file_open_dialog__t.html", null ],
    [ "Valve.Steamworks.HTML_FinishedRequest_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___finished_request__t.html", null ],
    [ "Valve.Steamworks.HTML_HideToolTip_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___hide_tool_tip__t.html", null ],
    [ "Valve.Steamworks.HTML_HorizontalScroll_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___horizontal_scroll__t.html", null ],
    [ "Valve.Steamworks.HTML_JSAlert_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___j_s_alert__t.html", null ],
    [ "Valve.Steamworks.HTML_JSConfirm_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___j_s_confirm__t.html", null ],
    [ "Valve.Steamworks.HTML_LinkAtPosition_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___link_at_position__t.html", null ],
    [ "Valve.Steamworks.HTML_NeedsPaint_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___needs_paint__t.html", null ],
    [ "Valve.Steamworks.HTML_NewWindow_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___new_window__t.html", null ],
    [ "Valve.Steamworks.HTML_OpenLinkInNewTab_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___open_link_in_new_tab__t.html", null ],
    [ "Valve.Steamworks.HTML_SearchResults_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___search_results__t.html", null ],
    [ "Valve.Steamworks.HTML_SetCursor_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___set_cursor__t.html", null ],
    [ "Valve.Steamworks.HTML_ShowToolTip_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___show_tool_tip__t.html", null ],
    [ "Valve.Steamworks.HTML_StartRequest_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___start_request__t.html", null ],
    [ "Valve.Steamworks.HTML_StatusText_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___status_text__t.html", null ],
    [ "Valve.Steamworks.HTML_UpdateToolTip_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___update_tool_tip__t.html", null ],
    [ "Valve.Steamworks.HTML_URLChanged_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___u_r_l_changed__t.html", null ],
    [ "Valve.Steamworks.HTML_VerticalScroll_t", "struct_valve_1_1_steamworks_1_1_h_t_m_l___vertical_scroll__t.html", null ],
    [ "Valve.Steamworks.HTTPRequestCompleted_t", "struct_valve_1_1_steamworks_1_1_h_t_t_p_request_completed__t.html", null ],
    [ "HTTPRequestCompleted_t", "struct_h_t_t_p_request_completed__t.html", null ],
    [ "Valve.Steamworks.HTTPRequestDataReceived_t", "struct_valve_1_1_steamworks_1_1_h_t_t_p_request_data_received__t.html", null ],
    [ "HTTPRequestDataReceived_t", "struct_h_t_t_p_request_data_received__t.html", null ],
    [ "HTTPRequestHeadersReceived_t", "struct_h_t_t_p_request_headers_received__t.html", null ],
    [ "Valve.Steamworks.HTTPRequestHeadersReceived_t", "struct_valve_1_1_steamworks_1_1_h_t_t_p_request_headers_received__t.html", null ],
    [ "IPCFailure_t", "struct_i_p_c_failure__t.html", null ],
    [ "IPCountry_t", "struct_i_p_country__t.html", null ],
    [ "ISteamAppList", "class_i_steam_app_list.html", null ],
    [ "Valve.Steamworks.ISteamAppList", "class_valve_1_1_steamworks_1_1_i_steam_app_list.html", [
      [ "Valve.Steamworks.CSteamAppList", "class_valve_1_1_steamworks_1_1_c_steam_app_list.html", null ]
    ] ],
    [ "ISteamApps", "class_i_steam_apps.html", null ],
    [ "Valve.Steamworks.ISteamApps", "class_valve_1_1_steamworks_1_1_i_steam_apps.html", [
      [ "Valve.Steamworks.CSteamApps", "class_valve_1_1_steamworks_1_1_c_steam_apps.html", null ]
    ] ],
    [ "ISteamAppTicket", "class_i_steam_app_ticket.html", null ],
    [ "Valve.Steamworks.ISteamClient", "class_valve_1_1_steamworks_1_1_i_steam_client.html", [
      [ "Valve.Steamworks.CSteamClient", "class_valve_1_1_steamworks_1_1_c_steam_client.html", null ]
    ] ],
    [ "ISteamClient", "class_i_steam_client.html", null ],
    [ "ISteamController", "class_i_steam_controller.html", null ],
    [ "Valve.Steamworks.ISteamController", "class_valve_1_1_steamworks_1_1_i_steam_controller.html", [
      [ "Valve.Steamworks.CSteamController", "class_valve_1_1_steamworks_1_1_c_steam_controller.html", null ]
    ] ],
    [ "ISteamFriends", "class_i_steam_friends.html", null ],
    [ "Valve.Steamworks.ISteamFriends", "class_valve_1_1_steamworks_1_1_i_steam_friends.html", [
      [ "Valve.Steamworks.CSteamFriends", "class_valve_1_1_steamworks_1_1_c_steam_friends.html", null ]
    ] ],
    [ "ISteamGameCoordinator", "class_i_steam_game_coordinator.html", null ],
    [ "Valve.Steamworks.ISteamGameServer", "class_valve_1_1_steamworks_1_1_i_steam_game_server.html", [
      [ "Valve.Steamworks.CSteamGameServer", "class_valve_1_1_steamworks_1_1_c_steam_game_server.html", null ]
    ] ],
    [ "ISteamGameServer", "class_i_steam_game_server.html", null ],
    [ "Valve.Steamworks.ISteamGameServerStats", "class_valve_1_1_steamworks_1_1_i_steam_game_server_stats.html", [
      [ "Valve.Steamworks.CSteamGameServerStats", "class_valve_1_1_steamworks_1_1_c_steam_game_server_stats.html", null ]
    ] ],
    [ "ISteamGameServerStats", "class_i_steam_game_server_stats.html", null ],
    [ "ISteamHTMLSurface", "class_i_steam_h_t_m_l_surface.html", null ],
    [ "Valve.Steamworks.ISteamHTMLSurface", "class_valve_1_1_steamworks_1_1_i_steam_h_t_m_l_surface.html", [
      [ "Valve.Steamworks.CSteamHTMLSurface", "class_valve_1_1_steamworks_1_1_c_steam_h_t_m_l_surface.html", null ]
    ] ],
    [ "Valve.Steamworks.ISteamHTTP", "class_valve_1_1_steamworks_1_1_i_steam_h_t_t_p.html", [
      [ "Valve.Steamworks.CSteamHTTP", "class_valve_1_1_steamworks_1_1_c_steam_h_t_t_p.html", null ]
    ] ],
    [ "ISteamHTTP", "class_i_steam_h_t_t_p.html", null ],
    [ "Valve.Steamworks.ISteamInventory", "class_valve_1_1_steamworks_1_1_i_steam_inventory.html", [
      [ "Valve.Steamworks.CSteamInventory", "class_valve_1_1_steamworks_1_1_c_steam_inventory.html", null ]
    ] ],
    [ "ISteamInventory", "class_i_steam_inventory.html", null ],
    [ "ISteamMatchmaking", "class_i_steam_matchmaking.html", null ],
    [ "Valve.Steamworks.ISteamMatchmaking", "class_valve_1_1_steamworks_1_1_i_steam_matchmaking.html", [
      [ "Valve.Steamworks.CSteamMatchmaking", "class_valve_1_1_steamworks_1_1_c_steam_matchmaking.html", null ]
    ] ],
    [ "ISteamMatchmakingPingResponse", "class_i_steam_matchmaking_ping_response.html", null ],
    [ "Valve.Steamworks.ISteamMatchmakingPingResponse", "class_valve_1_1_steamworks_1_1_i_steam_matchmaking_ping_response.html", [
      [ "Valve.Steamworks.CSteamMatchmakingPingResponse", "class_valve_1_1_steamworks_1_1_c_steam_matchmaking_ping_response.html", null ]
    ] ],
    [ "ISteamMatchmakingPlayersResponse", "class_i_steam_matchmaking_players_response.html", null ],
    [ "Valve.Steamworks.ISteamMatchmakingPlayersResponse", "class_valve_1_1_steamworks_1_1_i_steam_matchmaking_players_response.html", [
      [ "Valve.Steamworks.CSteamMatchmakingPlayersResponse", "class_valve_1_1_steamworks_1_1_c_steam_matchmaking_players_response.html", null ]
    ] ],
    [ "Valve.Steamworks.ISteamMatchmakingRulesResponse", "class_valve_1_1_steamworks_1_1_i_steam_matchmaking_rules_response.html", [
      [ "Valve.Steamworks.CSteamMatchmakingRulesResponse", "class_valve_1_1_steamworks_1_1_c_steam_matchmaking_rules_response.html", null ]
    ] ],
    [ "ISteamMatchmakingRulesResponse", "class_i_steam_matchmaking_rules_response.html", null ],
    [ "ISteamMatchmakingServerListResponse", "class_i_steam_matchmaking_server_list_response.html", null ],
    [ "Valve.Steamworks.ISteamMatchmakingServerListResponse", "class_valve_1_1_steamworks_1_1_i_steam_matchmaking_server_list_response.html", [
      [ "Valve.Steamworks.CSteamMatchmakingServerListResponse", "class_valve_1_1_steamworks_1_1_c_steam_matchmaking_server_list_response.html", null ]
    ] ],
    [ "Valve.Steamworks.ISteamMatchmakingServers", "class_valve_1_1_steamworks_1_1_i_steam_matchmaking_servers.html", [
      [ "Valve.Steamworks.CSteamMatchmakingServers", "class_valve_1_1_steamworks_1_1_c_steam_matchmaking_servers.html", null ]
    ] ],
    [ "ISteamMatchmakingServers", "class_i_steam_matchmaking_servers.html", null ],
    [ "ISteamMusic", "class_i_steam_music.html", null ],
    [ "Valve.Steamworks.ISteamMusic", "class_valve_1_1_steamworks_1_1_i_steam_music.html", [
      [ "Valve.Steamworks.CSteamMusic", "class_valve_1_1_steamworks_1_1_c_steam_music.html", null ]
    ] ],
    [ "ISteamMusicRemote", "class_i_steam_music_remote.html", null ],
    [ "Valve.Steamworks.ISteamMusicRemote", "class_valve_1_1_steamworks_1_1_i_steam_music_remote.html", [
      [ "Valve.Steamworks.CSteamMusicRemote", "class_valve_1_1_steamworks_1_1_c_steam_music_remote.html", null ]
    ] ],
    [ "ISteamNetworking", "class_i_steam_networking.html", null ],
    [ "Valve.Steamworks.ISteamNetworking", "class_valve_1_1_steamworks_1_1_i_steam_networking.html", [
      [ "Valve.Steamworks.CSteamNetworking", "class_valve_1_1_steamworks_1_1_c_steam_networking.html", null ]
    ] ],
    [ "Valve.Steamworks.ISteamParentalSettings", "class_valve_1_1_steamworks_1_1_i_steam_parental_settings.html", [
      [ "Valve.Steamworks.CSteamParentalSettings", "class_valve_1_1_steamworks_1_1_c_steam_parental_settings.html", null ]
    ] ],
    [ "ISteamParentalSettings", "class_i_steam_parental_settings.html", null ],
    [ "ISteamPS3OverlayRender", "class_i_steam_p_s3_overlay_render.html", null ],
    [ "ISteamPS3OverlayRenderHost", "class_i_steam_p_s3_overlay_render_host.html", null ],
    [ "Valve.Steamworks.ISteamRemoteStorage", "class_valve_1_1_steamworks_1_1_i_steam_remote_storage.html", [
      [ "Valve.Steamworks.CSteamRemoteStorage", "class_valve_1_1_steamworks_1_1_c_steam_remote_storage.html", null ]
    ] ],
    [ "ISteamRemoteStorage", "class_i_steam_remote_storage.html", null ],
    [ "ISteamScreenshots", "class_i_steam_screenshots.html", null ],
    [ "Valve.Steamworks.ISteamScreenshots", "class_valve_1_1_steamworks_1_1_i_steam_screenshots.html", [
      [ "Valve.Steamworks.CSteamScreenshots", "class_valve_1_1_steamworks_1_1_c_steam_screenshots.html", null ]
    ] ],
    [ "ISteamUGC", "class_i_steam_u_g_c.html", null ],
    [ "Valve.Steamworks.ISteamUGC", "class_valve_1_1_steamworks_1_1_i_steam_u_g_c.html", [
      [ "Valve.Steamworks.CSteamUGC", "class_valve_1_1_steamworks_1_1_c_steam_u_g_c.html", null ]
    ] ],
    [ "ISteamUnifiedMessages", "class_i_steam_unified_messages.html", null ],
    [ "Valve.Steamworks.ISteamUnifiedMessages", "class_valve_1_1_steamworks_1_1_i_steam_unified_messages.html", [
      [ "Valve.Steamworks.CSteamUnifiedMessages", "class_valve_1_1_steamworks_1_1_c_steam_unified_messages.html", null ]
    ] ],
    [ "Valve.Steamworks.ISteamUser", "class_valve_1_1_steamworks_1_1_i_steam_user.html", [
      [ "Valve.Steamworks.CSteamUser", "class_valve_1_1_steamworks_1_1_c_steam_user.html", null ]
    ] ],
    [ "ISteamUser", "class_i_steam_user.html", null ],
    [ "ISteamUserStats", "class_i_steam_user_stats.html", null ],
    [ "Valve.Steamworks.ISteamUserStats", "class_valve_1_1_steamworks_1_1_i_steam_user_stats.html", [
      [ "Valve.Steamworks.CSteamUserStats", "class_valve_1_1_steamworks_1_1_c_steam_user_stats.html", null ]
    ] ],
    [ "Valve.Steamworks.ISteamUtils", "class_valve_1_1_steamworks_1_1_i_steam_utils.html", [
      [ "Valve.Steamworks.CSteamUtils", "class_valve_1_1_steamworks_1_1_c_steam_utils.html", null ]
    ] ],
    [ "ISteamUtils", "class_i_steam_utils.html", null ],
    [ "Valve.Steamworks.ISteamVideo", "class_valve_1_1_steamworks_1_1_i_steam_video.html", [
      [ "Valve.Steamworks.CSteamVideo", "class_valve_1_1_steamworks_1_1_c_steam_video.html", null ]
    ] ],
    [ "ISteamVideo", "class_i_steam_video.html", null ],
    [ "ItemInstalled_t", "struct_item_installed__t.html", null ],
    [ "JoinClanChatRoomCompletionResult_t", "struct_join_clan_chat_room_completion_result__t.html", null ],
    [ "Valve.Steamworks.JoinClanChatRoomCompletionResult_t", "struct_valve_1_1_steamworks_1_1_join_clan_chat_room_completion_result__t.html", null ],
    [ "LeaderboardEntry_t", "struct_leaderboard_entry__t.html", null ],
    [ "Valve.Steamworks.LeaderboardEntry_t", "struct_valve_1_1_steamworks_1_1_leaderboard_entry__t.html", null ],
    [ "LeaderboardFindResult_t", "struct_leaderboard_find_result__t.html", null ],
    [ "Valve.Steamworks.LeaderboardFindResult_t", "struct_valve_1_1_steamworks_1_1_leaderboard_find_result__t.html", null ],
    [ "LeaderboardScoresDownloaded_t", "struct_leaderboard_scores_downloaded__t.html", null ],
    [ "Valve.Steamworks.LeaderboardScoresDownloaded_t", "struct_valve_1_1_steamworks_1_1_leaderboard_scores_downloaded__t.html", null ],
    [ "LeaderboardScoreUploaded_t", "struct_leaderboard_score_uploaded__t.html", null ],
    [ "Valve.Steamworks.LeaderboardScoreUploaded_t", "struct_valve_1_1_steamworks_1_1_leaderboard_score_uploaded__t.html", null ],
    [ "LeaderboardUGCSet_t", "struct_leaderboard_u_g_c_set__t.html", null ],
    [ "Valve.Steamworks.LeaderboardUGCSet_t", "struct_valve_1_1_steamworks_1_1_leaderboard_u_g_c_set__t.html", null ],
    [ "LED", "class_l_e_d.html", null ],
    [ "LicensesUpdated_t", "struct_licenses_updated__t.html", null ],
    [ "LobbyChatMsg_t", "struct_lobby_chat_msg__t.html", null ],
    [ "Valve.Steamworks.LobbyChatMsg_t", "struct_valve_1_1_steamworks_1_1_lobby_chat_msg__t.html", null ],
    [ "Valve.Steamworks.LobbyChatUpdate_t", "struct_valve_1_1_steamworks_1_1_lobby_chat_update__t.html", null ],
    [ "LobbyChatUpdate_t", "struct_lobby_chat_update__t.html", null ],
    [ "LobbyCreated_t", "struct_lobby_created__t.html", null ],
    [ "Valve.Steamworks.LobbyCreated_t", "struct_valve_1_1_steamworks_1_1_lobby_created__t.html", null ],
    [ "LobbyDataUpdate_t", "struct_lobby_data_update__t.html", null ],
    [ "Valve.Steamworks.LobbyDataUpdate_t", "struct_valve_1_1_steamworks_1_1_lobby_data_update__t.html", null ],
    [ "LobbyEnter_t", "struct_lobby_enter__t.html", null ],
    [ "Valve.Steamworks.LobbyEnter_t", "struct_valve_1_1_steamworks_1_1_lobby_enter__t.html", null ],
    [ "LobbyGameCreated_t", "struct_lobby_game_created__t.html", null ],
    [ "Valve.Steamworks.LobbyGameCreated_t", "struct_valve_1_1_steamworks_1_1_lobby_game_created__t.html", null ],
    [ "Valve.Steamworks.LobbyInvite_t", "struct_valve_1_1_steamworks_1_1_lobby_invite__t.html", null ],
    [ "LobbyInvite_t", "struct_lobby_invite__t.html", null ],
    [ "LobbyKicked_t", "struct_lobby_kicked__t.html", null ],
    [ "Valve.Steamworks.LobbyKicked_t", "struct_valve_1_1_steamworks_1_1_lobby_kicked__t.html", null ],
    [ "Valve.Steamworks.LobbyMatchList_t", "struct_valve_1_1_steamworks_1_1_lobby_match_list__t.html", null ],
    [ "LobbyMatchList_t", "struct_lobby_match_list__t.html", null ],
    [ "Valve.Steamworks.LowBatteryPower_t", "struct_valve_1_1_steamworks_1_1_low_battery_power__t.html", null ],
    [ "LowBatteryPower_t", "struct_low_battery_power__t.html", null ],
    [ "Main", "class_main.html", null ],
    [ "Valve.Steamworks.MatchMakingKeyValuePair_t", "struct_valve_1_1_steamworks_1_1_match_making_key_value_pair__t.html", null ],
    [ "MatchMakingKeyValuePair_t", "struct_match_making_key_value_pair__t.html", null ],
    [ "MicroTxnAuthorizationResponse_t", "struct_micro_txn_authorization_response__t.html", null ],
    [ "Valve.Steamworks.MicroTxnAuthorizationResponse_t", "struct_valve_1_1_steamworks_1_1_micro_txn_authorization_response__t.html", null ],
    [ "Stream::MultiTarget", "struct_stream_1_1_multi_target.html", null ],
    [ "Valve.Interop.NativeEntrypoints", "class_valve_1_1_interop_1_1_native_entrypoints.html", null ],
    [ "NewLaunchQueryParameters_t", "struct_new_launch_query_parameters__t.html", null ],
    [ "NumberOfCurrentPlayers_t", "struct_number_of_current_players__t.html", null ],
    [ "Valve.Steamworks.NumberOfCurrentPlayers_t", "struct_valve_1_1_steamworks_1_1_number_of_current_players__t.html", null ],
    [ "OLED", "class_o_l_e_d.html", null ],
    [ "P2PSessionConnectFail_t", "struct_p2_p_session_connect_fail__t.html", null ],
    [ "Valve.Steamworks.P2PSessionConnectFail_t", "struct_valve_1_1_steamworks_1_1_p2_p_session_connect_fail__t.html", null ],
    [ "P2PSessionRequest_t", "struct_p2_p_session_request__t.html", null ],
    [ "Valve.Steamworks.P2PSessionRequest_t", "struct_valve_1_1_steamworks_1_1_p2_p_session_request__t.html", null ],
    [ "Valve.Steamworks.P2PSessionState_t", "struct_valve_1_1_steamworks_1_1_p2_p_session_state__t.html", null ],
    [ "P2PSessionState_t", "struct_p2_p_session_state__t.html", null ],
    [ "PersonaStateChange_t", "struct_persona_state_change__t.html", null ],
    [ "Valve.Steamworks.PersonaStateChange_t", "struct_valve_1_1_steamworks_1_1_persona_state_change__t.html", null ],
    [ "Print", "class_print.html", [
      [ "Adafruit_CharacterOLED", "class_adafruit___character_o_l_e_d.html", null ],
      [ "Stream", "class_stream.html", [
        [ "SoftwareSerial", "class_software_serial.html", null ],
        [ "SoftwareSerial", "class_software_serial.html", null ],
        [ "TwoWire", "class_two_wire.html", null ],
        [ "TwoWire", "class_two_wire.html", null ]
      ] ],
      [ "Stream", "class_stream.html", null ]
    ] ],
    [ "SteamPS3Params_t::Ps3jpgInit_t", "struct_steam_p_s3_params__t_1_1_ps3jpg_init__t.html", null ],
    [ "SteamPS3Params_t::Ps3netInit_t", "struct_steam_p_s3_params__t_1_1_ps3net_init__t.html", null ],
    [ "SteamPS3Params_t::Ps3pngInit_t", "struct_steam_p_s3_params__t_1_1_ps3png_init__t.html", null ],
    [ "SteamPS3Params_t::Ps3sysutilUserInfo_t", "struct_steam_p_s3_params__t_1_1_ps3sysutil_user_info__t.html", null ],
    [ "PS3TrophiesInstalled_t", "struct_p_s3_trophies_installed__t.html", null ],
    [ "Valve.Steamworks.PS3TrophiesInstalled_t", "struct_valve_1_1_steamworks_1_1_p_s3_trophies_installed__t.html", null ],
    [ "PSNGameBootInviteResult_t", "struct_p_s_n_game_boot_invite_result__t.html", null ],
    [ "Valve.Steamworks.PSNGameBootInviteResult_t", "struct_valve_1_1_steamworks_1_1_p_s_n_game_boot_invite_result__t.html", null ],
    [ "QObject", null, [
      [ "BackEndSpace::BackEnd", "class_back_end_space_1_1_back_end.html", null ],
      [ "FrontEndSpace::FrontEnd", "class_front_end_space_1_1_front_end.html", null ]
    ] ],
    [ "RegisterActivationCodeResponse_t", "struct_register_activation_code_response__t.html", null ],
    [ "Valve.Steamworks.RegisterActivationCodeResponse_t", "struct_valve_1_1_steamworks_1_1_register_activation_code_response__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageAppSyncedClient_t", "struct_valve_1_1_steamworks_1_1_remote_storage_app_synced_client__t.html", null ],
    [ "RemoteStorageAppSyncedClient_t", "struct_remote_storage_app_synced_client__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageAppSyncedServer_t", "struct_valve_1_1_steamworks_1_1_remote_storage_app_synced_server__t.html", null ],
    [ "RemoteStorageAppSyncedServer_t", "struct_remote_storage_app_synced_server__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageAppSyncProgress_t", "struct_valve_1_1_steamworks_1_1_remote_storage_app_sync_progress__t.html", null ],
    [ "RemoteStorageAppSyncProgress_t", "struct_remote_storage_app_sync_progress__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageAppSyncStatusCheck_t", "struct_valve_1_1_steamworks_1_1_remote_storage_app_sync_status_check__t.html", null ],
    [ "RemoteStorageAppSyncStatusCheck_t", "struct_remote_storage_app_sync_status_check__t.html", null ],
    [ "RemoteStorageDeletePublishedFileResult_t", "struct_remote_storage_delete_published_file_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageDeletePublishedFileResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_delete_published_file_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageDownloadUGCResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_download_u_g_c_result__t.html", null ],
    [ "RemoteStorageDownloadUGCResult_t", "struct_remote_storage_download_u_g_c_result__t.html", null ],
    [ "RemoteStorageEnumeratePublishedFilesByUserActionResult_t", "struct_remote_storage_enumerate_published_files_by_user_action_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumeratePublishedFilesByUserActionResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_enumerate_published_files_by_user_action_result__t.html", null ],
    [ "RemoteStorageEnumerateUserPublishedFilesResult_t", "struct_remote_storage_enumerate_user_published_files_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumerateUserPublishedFilesResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_enumerate_user_published_files_result__t.html", null ],
    [ "RemoteStorageEnumerateUserSharedWorkshopFilesResult_t", "struct_remote_storage_enumerate_user_shared_workshop_files_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumerateUserSharedWorkshopFilesResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_enumerate_user_shared_workshop_files_result__t.html", null ],
    [ "RemoteStorageEnumerateUserSubscribedFilesResult_t", "struct_remote_storage_enumerate_user_subscribed_files_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumerateUserSubscribedFilesResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_enumerate_user_subscribed_files_result__t.html", null ],
    [ "RemoteStorageEnumerateWorkshopFilesResult_t", "struct_remote_storage_enumerate_workshop_files_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageEnumerateWorkshopFilesResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_enumerate_workshop_files_result__t.html", null ],
    [ "RemoteStorageFileReadAsyncComplete_t", "struct_remote_storage_file_read_async_complete__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageFileReadAsyncComplete_t", "struct_valve_1_1_steamworks_1_1_remote_storage_file_read_async_complete__t.html", null ],
    [ "RemoteStorageFileShareResult_t", "struct_remote_storage_file_share_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageFileShareResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_file_share_result__t.html", null ],
    [ "RemoteStorageFileWriteAsyncComplete_t", "struct_remote_storage_file_write_async_complete__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageFileWriteAsyncComplete_t", "struct_valve_1_1_steamworks_1_1_remote_storage_file_write_async_complete__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageGetPublishedFileDetailsResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_get_published_file_details_result__t.html", null ],
    [ "RemoteStorageGetPublishedFileDetailsResult_t", "struct_remote_storage_get_published_file_details_result__t.html", null ],
    [ "RemoteStorageGetPublishedItemVoteDetailsResult_t", "struct_remote_storage_get_published_item_vote_details_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageGetPublishedItemVoteDetailsResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_get_published_item_vote_details_result__t.html", null ],
    [ "RemoteStoragePublishedFileDeleted_t", "struct_remote_storage_published_file_deleted__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishedFileDeleted_t", "struct_valve_1_1_steamworks_1_1_remote_storage_published_file_deleted__t.html", null ],
    [ "RemoteStoragePublishedFileSubscribed_t", "struct_remote_storage_published_file_subscribed__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishedFileSubscribed_t", "struct_valve_1_1_steamworks_1_1_remote_storage_published_file_subscribed__t.html", null ],
    [ "RemoteStoragePublishedFileUnsubscribed_t", "struct_remote_storage_published_file_unsubscribed__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishedFileUnsubscribed_t", "struct_valve_1_1_steamworks_1_1_remote_storage_published_file_unsubscribed__t.html", null ],
    [ "RemoteStoragePublishedFileUpdated_t", "struct_remote_storage_published_file_updated__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishedFileUpdated_t", "struct_valve_1_1_steamworks_1_1_remote_storage_published_file_updated__t.html", null ],
    [ "RemoteStoragePublishFileProgress_t", "struct_remote_storage_publish_file_progress__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishFileProgress_t", "struct_valve_1_1_steamworks_1_1_remote_storage_publish_file_progress__t.html", null ],
    [ "Valve.Steamworks.RemoteStoragePublishFileResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_publish_file_result__t.html", null ],
    [ "RemoteStoragePublishFileResult_t", "struct_remote_storage_publish_file_result__t.html", null ],
    [ "RemoteStorageSetUserPublishedFileActionResult_t", "struct_remote_storage_set_user_published_file_action_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageSetUserPublishedFileActionResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_set_user_published_file_action_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageSubscribePublishedFileResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_subscribe_published_file_result__t.html", null ],
    [ "RemoteStorageSubscribePublishedFileResult_t", "struct_remote_storage_subscribe_published_file_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageUnsubscribePublishedFileResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_unsubscribe_published_file_result__t.html", null ],
    [ "RemoteStorageUnsubscribePublishedFileResult_t", "struct_remote_storage_unsubscribe_published_file_result__t.html", null ],
    [ "RemoteStorageUpdatePublishedFileResult_t", "struct_remote_storage_update_published_file_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageUpdatePublishedFileResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_update_published_file_result__t.html", null ],
    [ "RemoteStorageUpdateUserPublishedItemVoteResult_t", "struct_remote_storage_update_user_published_item_vote_result__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageUpdateUserPublishedItemVoteResult_t", "struct_valve_1_1_steamworks_1_1_remote_storage_update_user_published_item_vote_result__t.html", null ],
    [ "RemoteStorageUserVoteDetails_t", "struct_remote_storage_user_vote_details__t.html", null ],
    [ "Valve.Steamworks.RemoteStorageUserVoteDetails_t", "struct_valve_1_1_steamworks_1_1_remote_storage_user_vote_details__t.html", null ],
    [ "RemoveAppDependencyResult_t", "struct_remove_app_dependency_result__t.html", null ],
    [ "Valve.Steamworks.RemoveAppDependencyResult_t", "struct_valve_1_1_steamworks_1_1_remove_app_dependency_result__t.html", null ],
    [ "Valve.Steamworks.RemoveUGCDependencyResult_t", "struct_valve_1_1_steamworks_1_1_remove_u_g_c_dependency_result__t.html", null ],
    [ "RemoveUGCDependencyResult_t", "struct_remove_u_g_c_dependency_result__t.html", null ],
    [ "RTCDateTime", "struct_r_t_c_date_time.html", null ],
    [ "ScreenshotReady_t", "struct_screenshot_ready__t.html", null ],
    [ "Valve.Steamworks.ScreenshotReady_t", "struct_valve_1_1_steamworks_1_1_screenshot_ready__t.html", null ],
    [ "ScreenshotRequested_t", "struct_screenshot_requested__t.html", null ],
    [ "servernetadr_t", "classservernetadr__t.html", null ],
    [ "Valve.Steamworks.servernetadr_t", "struct_valve_1_1_steamworks_1_1servernetadr__t.html", null ],
    [ "SetPersonaNameResponse_t", "struct_set_persona_name_response__t.html", null ],
    [ "Valve.Steamworks.SetPersonaNameResponse_t", "struct_valve_1_1_steamworks_1_1_set_persona_name_response__t.html", null ],
    [ "SetUserItemVoteResult_t", "struct_set_user_item_vote_result__t.html", null ],
    [ "Valve.Steamworks.SetUserItemVoteResult_t", "struct_valve_1_1_steamworks_1_1_set_user_item_vote_result__t.html", null ],
    [ "Valve.Steamworks.SocketStatusCallback_t", "struct_valve_1_1_steamworks_1_1_socket_status_callback__t.html", null ],
    [ "SocketStatusCallback_t", "struct_socket_status_callback__t.html", null ],
    [ "StartPlaytimeTrackingResult_t", "struct_start_playtime_tracking_result__t.html", null ],
    [ "Valve.Steamworks.StartPlaytimeTrackingResult_t", "struct_valve_1_1_steamworks_1_1_start_playtime_tracking_result__t.html", null ],
    [ "Valve.Steamworks.SteamAPI", "class_valve_1_1_steamworks_1_1_steam_a_p_i.html", null ],
    [ "Valve.Steamworks.SteamAPICallCompleted_t", "struct_valve_1_1_steamworks_1_1_steam_a_p_i_call_completed__t.html", null ],
    [ "SteamAPICallCompleted_t", "struct_steam_a_p_i_call_completed__t.html", null ],
    [ "Valve.Steamworks.SteamAPIInterop", "class_valve_1_1_steamworks_1_1_steam_a_p_i_interop.html", null ],
    [ "Valve.Steamworks.SteamCallback_t", "struct_valve_1_1_steamworks_1_1_steam_callback__t.html", null ],
    [ "Valve.Steamworks.SteamID_t", "struct_valve_1_1_steamworks_1_1_steam_i_d__t.html", null ],
    [ "CSteamID::SteamID_t::SteamIDComponent_t", "struct_c_steam_i_d_1_1_steam_i_d__t_1_1_steam_i_d_component__t.html", null ],
    [ "Valve.Steamworks.SteamIDComponent_t", "struct_valve_1_1_steamworks_1_1_steam_i_d_component__t.html", null ],
    [ "SteamInventoryDefinitionUpdate_t", "struct_steam_inventory_definition_update__t.html", null ],
    [ "SteamInventoryEligiblePromoItemDefIDs_t", "struct_steam_inventory_eligible_promo_item_def_i_ds__t.html", null ],
    [ "Valve.Steamworks.SteamInventoryEligiblePromoItemDefIDs_t", "struct_valve_1_1_steamworks_1_1_steam_inventory_eligible_promo_item_def_i_ds__t.html", null ],
    [ "SteamInventoryFullUpdate_t", "struct_steam_inventory_full_update__t.html", null ],
    [ "Valve.Steamworks.SteamInventoryFullUpdate_t", "struct_valve_1_1_steamworks_1_1_steam_inventory_full_update__t.html", null ],
    [ "SteamInventoryResultReady_t", "struct_steam_inventory_result_ready__t.html", null ],
    [ "Valve.Steamworks.SteamInventoryResultReady_t", "struct_valve_1_1_steamworks_1_1_steam_inventory_result_ready__t.html", null ],
    [ "Valve.Steamworks.SteamItemDetails_t", "struct_valve_1_1_steamworks_1_1_steam_item_details__t.html", null ],
    [ "SteamItemDetails_t", "struct_steam_item_details__t.html", null ],
    [ "Valve.Steamworks.SteamParamStringArray_t", "struct_valve_1_1_steamworks_1_1_steam_param_string_array__t.html", null ],
    [ "SteamParamStringArray_t", "struct_steam_param_string_array__t.html", null ],
    [ "SteamParentalSettingsChanged_t", "struct_steam_parental_settings_changed__t.html", null ],
    [ "SteamPS3Memory_t", "struct_steam_p_s3_memory__t.html", null ],
    [ "SteamPS3Params_t", "struct_steam_p_s3_params__t.html", null ],
    [ "SteamServerConnectFailure_t", "struct_steam_server_connect_failure__t.html", null ],
    [ "Valve.Steamworks.SteamServerConnectFailure_t", "struct_valve_1_1_steamworks_1_1_steam_server_connect_failure__t.html", null ],
    [ "SteamServersConnected_t", "struct_steam_servers_connected__t.html", null ],
    [ "Valve.Steamworks.SteamServersDisconnected_t", "struct_valve_1_1_steamworks_1_1_steam_servers_disconnected__t.html", null ],
    [ "SteamServersDisconnected_t", "struct_steam_servers_disconnected__t.html", null ],
    [ "SteamShutdown_t", "struct_steam_shutdown__t.html", null ],
    [ "Valve.Steamworks.SteamUGCDetails_t", "struct_valve_1_1_steamworks_1_1_steam_u_g_c_details__t.html", null ],
    [ "SteamUGCDetails_t", "struct_steam_u_g_c_details__t.html", null ],
    [ "SteamUGCQueryCompleted_t", "struct_steam_u_g_c_query_completed__t.html", null ],
    [ "Valve.Steamworks.SteamUGCQueryCompleted_t", "struct_valve_1_1_steamworks_1_1_steam_u_g_c_query_completed__t.html", null ],
    [ "Valve.Steamworks.SteamUGCRequestUGCDetailsResult_t", "struct_valve_1_1_steamworks_1_1_steam_u_g_c_request_u_g_c_details_result__t.html", null ],
    [ "SteamUGCRequestUGCDetailsResult_t", "struct_steam_u_g_c_request_u_g_c_details_result__t.html", null ],
    [ "SteamUnifiedMessagesSendMethodResult_t", "struct_steam_unified_messages_send_method_result__t.html", null ],
    [ "Valve.Steamworks.SteamUnifiedMessagesSendMethodResult_t", "struct_valve_1_1_steamworks_1_1_steam_unified_messages_send_method_result__t.html", null ],
    [ "Valve.Steamworks.StopPlaytimeTrackingResult_t", "struct_valve_1_1_steamworks_1_1_stop_playtime_tracking_result__t.html", null ],
    [ "StopPlaytimeTrackingResult_t", "struct_stop_playtime_tracking_result__t.html", null ],
    [ "Valve.Steamworks.StoreAuthURLResponse_t", "struct_valve_1_1_steamworks_1_1_store_auth_u_r_l_response__t.html", null ],
    [ "StoreAuthURLResponse_t", "struct_store_auth_u_r_l_response__t.html", null ],
    [ "SubmitItemUpdateResult_t", "struct_submit_item_update_result__t.html", null ],
    [ "Valve.Steamworks.SubmitItemUpdateResult_t", "struct_valve_1_1_steamworks_1_1_submit_item_update_result__t.html", null ],
    [ "UserAchievementIconFetched_t", "struct_user_achievement_icon_fetched__t.html", null ],
    [ "Valve.Steamworks.UserAchievementIconFetched_t", "struct_valve_1_1_steamworks_1_1_user_achievement_icon_fetched__t.html", null ],
    [ "Valve.Steamworks.UserAchievementStored_t", "struct_valve_1_1_steamworks_1_1_user_achievement_stored__t.html", null ],
    [ "UserAchievementStored_t", "struct_user_achievement_stored__t.html", null ],
    [ "UserFavoriteItemsListChanged_t", "struct_user_favorite_items_list_changed__t.html", null ],
    [ "Valve.Steamworks.UserFavoriteItemsListChanged_t", "struct_valve_1_1_steamworks_1_1_user_favorite_items_list_changed__t.html", null ],
    [ "Valve.Steamworks.UserStatsReceived_t", "struct_valve_1_1_steamworks_1_1_user_stats_received__t.html", null ],
    [ "UserStatsReceived_t", "struct_user_stats_received__t.html", null ],
    [ "UserStatsStored_t", "struct_user_stats_stored__t.html", null ],
    [ "Valve.Steamworks.UserStatsStored_t", "struct_valve_1_1_steamworks_1_1_user_stats_stored__t.html", null ],
    [ "Valve.Steamworks.UserStatsUnloaded_t", "struct_valve_1_1_steamworks_1_1_user_stats_unloaded__t.html", null ],
    [ "UserStatsUnloaded_t", "struct_user_stats_unloaded__t.html", null ],
    [ "USI_TWI", "class_u_s_i___t_w_i.html", null ],
    [ "USI_TWI_state", "union_u_s_i___t_w_i__state.html", null ],
    [ "Valve.Steamworks.ValidateAuthTicketResponse_t", "struct_valve_1_1_steamworks_1_1_validate_auth_ticket_response__t.html", null ],
    [ "ValidateAuthTicketResponse_t", "struct_validate_auth_ticket_response__t.html", null ],
    [ "Valve.Steamworks.ValvePackingSentinel_t", "struct_valve_1_1_steamworks_1_1_valve_packing_sentinel__t.html", null ],
    [ "ValvePackingSentinel_t", "struct_valve_packing_sentinel__t.html", null ]
];